### ISSUE TITLE
Overflow in tel_id column of Array_Info table

### ISSUE THREAD

**Issue by aribrill** [cta-observatory/image-extractor#21]
The tel_ids for SST1 telescopes go from 220-255, followed by 0-33, in what appears to be an overflow error. This results in tel_ids being repeated, so they can't be used as unique keys. 

I suppose the relevant line in image_extractor.py is line 240, `arr_row["tel_id"] = tel_id`, but it's not clear to me why that would cause this error.

**Comment by bryankim96** [comment]
Now fixed in b61f883dd53e90895f2b6f0faae3f7e2f97c2bb6 and 549698cb775a371200e5cffd53d95f63fbbe5693.
